# Generated by Django 6.0.2 on 2026-04-22 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_user_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesinvoice',
            name='invoiceNum',
        ),
        migrations.RemoveField(
            model_name='salesinvoice',
            name='salespersonID',
        ),
    ]
