# Generated by Django 6.0.2 on 2026-04-22 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_salesinvoice_invoicenum_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='userID',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='store.user'),
        ),
    ]
