# Generated by Django 6.0.2 on 2026-04-22 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_notification_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoice',
            name='location',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.location'),
        ),
    ]
