# Generated by Django 6.0.2 on 2026-04-22 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_salesinvoice_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesinvoice',
            old_name='location',
            new_name='locationID',
        ),
    ]
