# Generated by Django 6.0.2 on 2026-04-25 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
        ('store', '0006_rename_location_salesinvoice_locationid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorial',
            name='roleID',
        ),
        migrations.AlterField(
            model_name='notification',
            name='tutorialID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.tutorial'),
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Tutorial',
        ),
    ]
