# Generated by Django 6.0.2 on 2026-04-25 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_remove_tutorial_roleid_alter_notification_tutorialid_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SalesInvoice',
            new_name='Order',
        ),
    ]
