# Generated by Django 6.0.2 on 2026-04-25 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_rename_salesinvoice_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='invoiceID',
            new_name='OrderID',
        ),
    ]
