# Generated by Django 6.0.2 on 2026-04-25 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_rename_invoiceid_notification_orderid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='OrderID',
            new_name='orderID',
        ),
    ]
